web/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  namespace :client do
    resources :orders
  end
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web/app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :restrict_with_exception

  def as_json(args)
    super.merge({
      location: orders.first.location,
      commodities: orders.group_by(&:commodity).map do |commodity, orders|
        "#{commodity}: #{orders.map(&:quantity).map(&:to_i).sum()}"
      end
    })
  end
end

web/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :delivery, optional: true

  validates :commodity, :location, :quantity, presence: true
  validates :quantity, numericality: { less_than_or_equal_to: 100, greater_than: 0 }

  def status
    return 'waiting' unless ack?
    return 'processing' if delivery.nil?
    return 'in delivery' unless delivery.delivered?
    'delivered'
  end

  def as_json(args)
    super.merge({
      status: status
    })
  end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/client/orders_controller.rb
class Client::OrdersController < ApplicationController
  def index
    @order = Order.new(location: 'Location A', commodity: 'Commodity A', quantity: 10)
    @orders = Order.all.order(created_at: :desc).limit(20)
    @deliveries = Delivery.includes(:orders).all.order(created_at: :desc).limit(15)
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      EventBus.order_created(@order)
      @order.update!(ack: true)
      head 200
    else
      @orders = Order.all
      render :index
    end
  end

  private

  def order_params
    params.require(:order).permit(:location, :quantity, :commodity)
  end
end

web/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/views/client/orders/_form.html.erb
<%= simple_form_for [:client, order], remote: true do |f| %>
  <%= f.input :location, as: :hidden %>
  <%= f.input :commodity, as: :hidden %>
  <%= f.input :quantity, as: :hidden %>
  <%= f.submit message, class: 'btn btn-primary' %>
<% end %>

web/app/views/client/orders/index.html.erb
<div class="app">
  <div class="app__form">
    <div class="app__header">
      <h2>1. Make some orders</h2>
    </div>

    <%= render 'form', order: Order.new(location: 'Office', commodity: 'Pen', quantity: 10), message: '10 pens to office' %>
    <%= render 'form', order: Order.new(location: 'Office', commodity: 'Chair', quantity: 2), message: '2 chairs to office' %>
    <%= render 'form', order: Order.new(location: 'Storage', commodity: 'Hat', quantity: 5), message: '5 hats to storage' %>
    <%= render 'form', order: Order.new(location: 'Storage', commodity: 'Pen', quantity: 8), message: '8 pens to storage' %>
  </div>

  <div class="app__list">
    <div class="app__header">
      <h2>2. See the raw orders <small>(reload the page to see status changes)</small></h2>
    </div>

    <table id="orders-table">
      <thead>
        <tr>
          <th>Location</th>
          <th>Commodity</th>
          <th>Quantity</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr id="order-<%= order.id %>">
            <td><%= order.location %></td>
            <td><%= order.commodity %></td>
            <td><%= order.quantity %></td>
            <td><%= order.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="app__list">
    <div class="app__header">
      <h2>3. Wait for batches to appear <small>(grouped by location; batches are created every 5 seconds; max batch size is 5 orders)</small></h2>
    </div>

    <table id="deliveries-table">
      <thead>
        <tr>
          <th>Location</th>
          <th>Details</th>
        </tr>
      </thead>
      <tbody>
        <% @deliveries.each do |delivery| %>
          <tr id="delivery-<%= delivery.id %>">
            <td><%= delivery.orders.first.location %></td>
            <td>
              <% delivery.orders.group_by(&:commodity).map do |commodity, orders| %>
                <%= "#{commodity}: #{orders.map(&:quantity).map(&:to_i).sum()}" %>
                <br/>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Lato:400,900&amp;subset=latin-ext" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

web/app/views/pages/home.html.erb
<div class="app app--home">
  <h1>Welcome to Rabbits</h1>
  <div class="app__actions">
    <%= link_to "Let's start!", client_orders_path, class: 'btn btn-primary' %>
  </div>
</div>